### ISSUE TITLE
Index array with result of overloaded method

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nielsAD/lape#34] opened 2015-03-21 17:24 UTC
```
What will reproduce the problem?
var Arr:Array of Integer = [0,0];
begin
  Arr[ round(1) ];
end.

What is the expected output? What do you see instead?
Error: Don't know which overloaded method to call with params (Int32) at line 6

Which version are you using?
c96f612e0066	

Please provide any additional information below.
This happens whenever you try to index an array with the result of any 
overloaded method. If methods is not overloaded it works, IE: `Arr[ ceil(1) ]` 
works fine.

```

Original issue reported on code.google.com by `JarlHo...@gmail.com` on 9 Sep 2014 at 1:06

**Comment by nielsAD** [comment] 2015-10-01 21:14
Should be fixed with 203e74fbe1b4b08be11a2f621906600b4cadf240. Prefer integer overloaded method since 50cd2d23772a0241451f907c19eae4b5d6665281.

**Closed by nielsAD** 2015-10-01 21:14 UTC
Labels: auto-migrated, Priority-Low, Type-Defect

**Comment by Olly-** [comment] 2015-10-04 00:44
@nielsAD Small confusion here, the problem isn't directly related to round but with every overloaded method use this as a example:

```
var
  a: array of Integer = [5..10];

function getIndex(): Integer;
begin
end;

function getIndex(b: Boolean): Integer; overload;
begin
  if (b) then
    Result := 1;
end;

begin
  Writeln(a[getIndex(True)]);
end;                         
```

This used to previously work fine (even the round example). I suspect this bug was introduced in the August 2014 commits.

**Comment by WarPie** [comment] 2015-10-04 07:22
Myeah as Olly says I think (without having tested your code) that you have misunderstood the problem.

The example used was:
> `function Round(x:Extended): Integer` 
Indexing arrays with the result of this should work.
It does however not work. This is because Round is an OverloadMethod, I suspect that resolving the result-type of OverloadMethods has failed (EvalRes), causing this bizarre issue.

**Comment by nielsAD** [comment] 2015-10-04 11:00
@Olly- your example compiles for me and writes 6 (as I would expect?).

@WarPie I pushed a fix that should the prevent the error you are getting when compiling Simba. Could you elaborate on "failing at just about everything possible"?

**Comment by WarPie** [comment] 2015-10-04 19:26
@nielsAD - sorry it was quite late when I wrote that. This shows the issue I get with Lape.exe: http://i.imgur.com/FOOmZ8y.png

I also got the same compile-time exception "Cannot prepare object" when trying to call some FFI method using Simba with your latest Lape.

And yes, the issue seems to be solved... even tho I struggle to make sense of the fix here.
