### ISSUE TITLE
ToString() error on Sets.

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#78] opened 2016-06-08 18:45 UTC
program HelloSetWorld;
uses display;

type
   Days=(Sun=0, Mon, Tue, Wed, Thr, Fri, Sat);
   DaysWorked=Set of Days;

var
   Schedule:DaysWorked;

begin
   Schedule:=[Mon, Wed, Thr, Fri];
   Writeln('This week I work 9-5 on ',Schedule);
   Schedule+=[Tue];
   Schedule-=[Thr];
   Writeln('Next week I work 9-5 on ',Schedule);
   ReadKey;
end.

Both writeln's return: Type expected at line 1, column 89 in file "!addGlobalFuncBdy (ToString)"

How do I fix?

**Comment by WarPie** [comment] 2016-06-08 19:27
can't be reproduced in any of the lape version I have, and I have versions dating back many years, and I also have the latest lape.

The output I get is:
```
This week I work 9-5 on [Mon, Wed, Thr, Fri]
Next week I work 9-5 on [Mon, Tue, Wed, Fri]
```

**Comment by nielsAD** [comment] 2016-07-10 18:17
Thanks for testing @WarPie. I also cannot reproduce this issue with the latest version. Please let me know if this is still an issue for you when you update Lape. I'll close this for now.

**Closed by nielsAD** 2016-07-10 18:17 UTC
