### ISSUE TITLE
Extended syntax: Infinite loop on compilation

### ISSUE THREAD

**Issue by WarPie** [nielsAD/lape#48] opened 2015-11-06 09:18 UTC
This extra `end` (line 8) will cause lape to go into some sort of infinite loop when compiling a script. 
```pascal
{$X+}

procedure Foo();
begin
end;

end; //extra end

begin
end. 
```

**Comment by nielsAD** [comment] 2015-12-05 22:24
Thanks for reporting. SRL/Lape#17 is a duplicate of this. As noted there, this should be fixed :)

**Closed** 2015-12-05 22:25 UTC
